### ISSUE TITLE
Question about IL embeddings in your paper

### ISSUE THREAD

**Issue by Aatlantise** [dair-iitd/openie6#11]
Hello,

openie6 is very interesting both in its performance and its approach to Open IE via grid labeling. Thank you for sharing your work.

In your paper, you only retain the embeddings of first word-piece for words that were broken into multiple word-pieces, instead of summing or using another technique to combine the word-piece embeddings.

Is there a particular reason why?

Thank you!

**Comment by SaiKeshav** [comment]
Thank you for your interest in our work. We experiment with two other strategies - picking the last word piece and averaging them. Both of them lead to similar performance. Hence, we decided to go ahead with using the first word-piece.

**Comment by Aatlantise** [comment]
Much thanks for your kind response :)

I have another question--in addition to the ILs, label embeddings are also generated and passed onto subsequent iterations. Are label embeddings one-hot vectors of length 6 (NONE, ARG1, ARG2, LOC, TIME, REL)? or is there a more complex way of computing them?
