### ISSUE TITLE
When task = ='conj ', there is a problem with the training data format

### ISSUE THREAD

**Issue by 123zzw** [dair-iitd/openie6#13]
Thank you for looking at my question in your busy schedule. I want to know how the data format is generated and what tools are used when task = conj
![image](https://user-images.githubusercontent.com/65516153/139013574-daf76ed8-da12-4541-880b-2da7b43764e4.png)

**Comment by SaiKeshav** [comment]
Hi. Probably too late to help you (sorry for that!) but in case others stumble across this issue, I have given a detailed description over here: https://github.com/dair-iitd/openie6/issues/7#issuecomment-1250005821
