### ISSUE TITLE
crash with curr_line_num referenced before assignment

### ISSUE THREAD

**Issue by sreiling** [dair-iitd/openie6#15]
run.py crashed on me with the following exception:

```
Traceback (most recent call last):
  File "run.py", line 469, in <module>
    main(hyperparams)
  File "run.py", line 459, in main
    train_dataloader, val_dataloader, test_dataloader, all_sentences)
  File "run.py", line 245, in splitpredict
    if curr_line_num not in no_extractions:
UnboundLocalError: local variable 'curr_line_num' referenced before assignment
```

Looking at the code, it looks like curr_line_num is only initialized when the for loop is executed at least once, which seems not to be true in my example.

**Comment by SaiKeshav** [comment]
Thanks for raising the issue. It seems to fail when the first sentence has no extractions. I have pushed a commit where the initialization is correctly done before the for loop.
