### ISSUE TITLE
Is there a way to get dependency parse outputs in addition to OpenIE ones?

### ISSUE THREAD

**Issue by saiprabhakar** [dair-iitd/openie6#17]
HI, I am trying to use both the OpenIE outputs and DP outputs for a sentence. Is it possible to get both from the same model/pipeline?

**Comment by SaiKeshav** [comment]
Sorry, we don't support this. The model only generates OpenIE outputs without using any dependency parse information.

**Comment by saiprabhakar** [comment]
got it, Thanks.
