### ISSUE TITLE
error for downloading model

### ISSUE THREAD

**Issue by euniceyliu** [dair-iitd/openie6#18]
I tried to download the model by doing 

`zenodo_get 4055395`

but i kept getting the following error:

```
Too many errors.
Download is aborted.
```

I am not sure how to fix this.

**Comment by SaiKeshav** [comment]
The above command does work for me

![image](https://user-images.githubusercontent.com/12623332/189028603-b272cf26-4546-4155-96c5-ed00a5dd58a8.png)

1. Can you please check if there are any network connectivity issues from your side? 
2. Can you update your zenodo_get commandline using `pip install -U zenodo_get`
