### ISSUE TITLE
Installation Issue

### ISSUE THREAD

**Issue by amandalmia14** [dair-iitd/openie6#3]
OS: Windows 10
Base Environment: Ananconda

When I try to install the requirements.txt as per given instruction in the README file, I get the below error.

![image](https://user-images.githubusercontent.com/13628323/98245297-b8263800-1f96-11eb-9170-ce720f0bd180.png)

**Comment by Martin36** [comment]
I get a similar problem when trying to install the dependencies on Windows. The issue seems to be with installing `jsonnet` on Windows, as described here: https://github.com/google/jsonnet/issues/476

Hope that helps

**Comment by amandalmia14** [comment]
@Martin36  Yes it did worked. I installed jsonnet via `pip install -e git+https://github.com/Toilal/jsonnet.git#egg=jsonnet`
Uncommented the jsonnet in the requirements.txt file and did then install all the packages.
