### ISSUE TITLE
Dependencies conflict during installation

### ISSUE THREAD

**Issue by lighteternal** [dair-iitd/openie6#5]
Hi and many thanks for the new Openie version. 

I had some issues during installation on a clean environment. I followed the instructions for the creation of a new conda env and upon installing the reqs I ended up with unresolvable dependency conflicts. 

The only way to fix this was to loosen the requirements from the requirements.txt file. Attached you can find the version that worked for me (cpu only). 
[requirements.txt](https://github.com/dair-iitd/openie6/files/5709190/requirements.txt)

It would be useful to know if anyone else faces the same issue.

**Comment by moinnadeem** [comment]
I also faced the same issue; does anyone have recommendations?

**Comment by alexeyev** [comment]
> worked for me (cpu only)
It seems that your method works with GPU as well. At least in my case.

**Comment by SaiKeshav** [comment]
Thanks for raising the issue! and sorry for the complete lack of response from my side. Resolved this bug in the latest commit. The spacy in allennlp is not being used in the code at all. So removed it from the requirements in allennlp.
